[toolchain]
anchor_version = "0.29.0"

[features]
resolution = true
skip-lint = false

[programs.devnet]
flipsol = "BTU8kuz95iPH6XqBMp7a4VEsLhdco62s9H81Jt6G4GQL"

[programs.localnet]
flipsol = "BTU8kuz95iPH6XqBMp7a4VEsLhdco62s9H81Jt6G4GQL"

[programs.mainnet]
flipsol = "BTU8kuz95iPH6XqBMp7a4VEsLhdco62s9H81Jt6G4GQL"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
initialize = "ts-node scripts/initialize.ts"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 10000
shutdown_wait = 2000
upgradeable = false
